version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r mysite/requirements.txt
  build:
    commands:
      # - python -m unittest discover -s mysite
artifacts:
  files:
    - '**/*'
  base-directory: mysite