version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.7
  pre_build:
    commands:
      - pip install -r mysite/requirements.txt
  build:
    commands:
      # - python -m unittest discover -s mysite
  post-build:
    commands:
      - echo "post deploy"      
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*
  # base-directory: mysite